# Generated by Django 4.1 on 2023-02-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_after",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
