# Generated by Django 4.1 on 2023-02-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart_shop", "0004_alter_product_discount_alter_product_price_after"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishitem", old_name="cart", new_name="WishList",
        ),
        migrations.RemoveField(model_name="wishitem", name="quantity",),
    ]
