# Generated by Django 4.1 on 2023-02-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart_shop", "0005_rename_cart_wishitem_wishlist_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishitem", unique_together={("WishList", "product")},
        ),
    ]
